"""changed user model

Revision ID: 48f7228d3947
Revises: 5fdc532b409a
Create Date: 2021-09-17 12:11:39.657073

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '48f7228d3947'
down_revision = '5fdc532b409a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
